### ISSUE TITLE
Would you be willing to merge a PR with TypeScript definitions?

### ISSUE THREAD

**Issue by dmeenhuis** [hirviid/react-redux-fetch#10]
Hi,

I saw that you are using Flow for type checking. I'm using TypeScript myself and I've created a set of definitions for this library.

I'd be willing to submit a PR with the definitions I have now. Perhaps that would be useful to potential other TypeScript users of this library.

Let me know :)

**Comment by hirviid** [comment]
Cool, thanks for adding this! Available in react-redux-fetch@0.6.6
