### ISSUE TITLE
Rejection handling doesn't seem to be working

### ISSUE THREAD

**Issue by dmeenhuis** [hirviid/react-redux-fetch#12]
Hi,

I have a component that makes a ``GET`` request to an API endpoint. When this API call results in a non-success status code (i.e. 400), I would have expected the fetch state to be ``rejected``.

Right now, this is not the case. When this situation occurs, the state is set to ``fulfilled``. 

I suspect it has something to do with the following line:

https://github.com/hirviid/react-redux-fetch/blob/master/src/utils/handleResponse.js#L4

Since an error response has no ``content-length``, it ends up in this if-branch, but that doesn't actually reject the promise.

**Comment by dmeenhuis** [comment]
Yes, that sounds reasonable 👍

**Comment by dmeenhuis** [comment]
Any idea when you'll publish the new version? :)

**Comment by hirviid** [comment]
Now! :) 
Available in react-redux-fetch@0.8.0

**Comment by dmeenhuis** [comment]
Haha awesome, thanks! :)
