### ISSUE TITLE
Disable for server side rendering?

### ISSUE THREAD

**Issue by sleungcy** [hirviid/react-redux-fetch#15]
Thanks very much for this amazing gem. How can I disable the fetch during server side rendering? If  I just not apply the middleware in the server side, would that be sufficient?

**Comment by hirviid** [comment]
Hi @sleungcy, indeed, the middleware takes care of making the actual request. So if you only apply the middleware client side you should be OK. 

There is an alternative way: You can write your own `fetchRequest` function (https://github.com/hirviid/react-redux-fetch/blob/master/src/middleware/fetchRequest.js) where you implement a conditional which checks if it is server or client calling the code, and register it with every request method, e.g.:
```javascript
import { container } from 'react-redux-fetch';

container.changeRequestMethodConfig('get', 'middleware', myFetchRequest);
container.changeRequestMethodConfig('post', 'middleware', myFetchRequest);
container.changeRequestMethodConfig('put', 'middleware', myFetchRequest);
container.changeRequestMethodConfig('delete', 'middleware', myFetchRequest);
```

**Comment by sleungcy** [comment]
Hi hirviid, thanks for the explanation and examples. 👍
