### ISSUE TITLE
Refetches with incorrect data if the request URL is dynamic and the component is updated

### ISSUE THREAD

**Issue by dmeenhuis** [hirviid/react-redux-fetch#2]
Hi,

I'm playing around with this library, since it appears to bridge the gap I found between Redux and Refetch. Generally it seems to be working, but I'm running into a strange issue.

The API that I call from my component, contains a request parameter that can possibly change for each request. Example code:

```javascript
export default connect((props) => {
    return [
      {
        resource: 'users',
        force: true,
        request: {
          url: `/service/authorization/company/${props.params.companyId}/users`
        }
      }
    ];
  }
)(UsersOverview));
```

The value in ``params.companyId`` is passed down from React Router, into the component. Now, for the initial render from a route, this works just fine. I can see the data being fetched and it ends up in my component.

However, when I update the route so that a new ``companyId`` is passed in, the fetch is instead called with the old value.

I tried playing around with the ``force`` and ``comparison`` parameters, but to no avail.

I have this bit in my component, to execute the fetch again when the props change:

```javascript
componentWillReceiveProps(nextProps) {
  if (this.props.params.companyId !== nextProps.params.companyId) {
    this.props.dispatchUsersGet();
  }
}
```

It appears that something of the original request action is floating around, which causes it to be executed with the old request URL, instead of the updated one.

Any idea what's going on here?

**Comment by hirviid** [comment]
Hi @dmeenhuis 

I will look into it. 

For now you could use a little workaround, passing the companyId to the dispatchUsersGet function:

```jsx
export default connect((props) => {
    return [
      {
        resource: 'users',
        force: true,
        request: companyId => ({ // declare 'request' as a function, receiving companyId as a param
          url: `/service/authorization/company/${companyId}/users`
        })
      }
    ];
  }
)(UsersOverview));
```

```jsx
componentWillReceiveProps(nextProps) {
  if (this.props.params.companyId !== nextProps.params.companyId) {
    this.props.dispatchUsersGet(nextProps.params.companyId); // pass companyId
  }
}
```

**Comment by dmeenhuis** [comment]
Hi, thanks for your prompt reply.

That indeed appears to fix the issue. I was actually looking to solve it in a similar way, but I must have missed that from the docs :) 

I would expect my original version to work as well, but I suppose doing it like this makes sense.

**Comment by hirviid** [comment]
I think it should work without passing the id explicitly. But you'll need to use `nextProps` in stead of `this.props` in componentWillReceiveProps:

```js
componentWillReceiveProps(nextProps) {
  if (this.props.params.companyId !== nextProps.params.companyId) {
    nextProps.dispatchUsersGet();
  }
}
```

**Comment by dmeenhuis** [comment]
Ahh, interesting. Hadn't tried that before, that may very well fix my issue. Will try it later this evening and I'll report back :)
