### ISSUE TITLE
How do I parse HTML response

### ISSUE THREAD

**Issue by jikotw74** [hirviid/react-redux-fetch#20]
It always handle response via JSON
Is there any way to parse a HTML response?

**Comment by hirviid** [comment]
You could override the default "handleResponse" function (see https://github.com/hirviid/react-redux-fetch/blob/master/src/utils/handleResponse.js).

To override, register your own handleResponse function with something like:
```JavaScript
import { container } from 'react-redux-fetch';

container.setUtil('handleResponse', myCustomResponseHandler);
```
