### ISSUE TITLE
jsonp support

### ISSUE THREAD

**Issue by Fxlr8** [hirviid/react-redux-fetch#21]
Hi, I am trying to add fetch-jsonp requests. Basically, Jsonp is like a regular JSON request, but it can deal with CORS and supports GET requests only. This is a workaround to make cross-origin fetch requests from browsers. There is a nice 3rd party library wrapper for it here https://github.com/camsong/fetch-jsonp.

I added my own method using `container` API
```
container.registerRequestMethod('jsonp', {
	method: 'jsonp', // The request method
	middleware: JSONPFetchRequest, 
	reducer: getReducer
})
```
Then i just copied your fetchRequest middleware and replaced `fetch` with `jsonFetch`, they have similar api
```
import container from 'react-redux-fetch/lib/container'
import onFulfillment from 'react-redux-fetch/lib/utils/onFulfillment'
import onRejection from 'react-redux-fetch/lib/utils/onRejection'
import fetchJsonp from 'fetch-jsonp'

const JSONPFetchRequest = (store, next, action) => {
	const req = container.getDefinition('requestBuilder').getArgument('build')(action.request.url, {
		method: action.method,
		body: action.request.body,
		headers: action.request.headers
	})
	const meta = action.request.meta || {}

	return fetchJsonp(req.url)
		.then((response) => {
			meta.response = response
			return response
		})
		.then(container.getUtil('handleResponse'))
		.then(
			onFulfillment(store, next, action, meta),
			onRejection(store, next, action, meta),
		)
}

export default JSONPFetchRequest
```
This is not working as expected. The request itself runs fine, Jsonp response looks like this
```
{ok: true, json: ƒ}
```
Seems like your `handleResponse` util does not like `fetch-jsonp` responses or something. JSONP_REJECT action gets dispatched
```
{
  type: 'react-redux-fetch/JSONP_REJECT',
  resource: {
    name: 'foo'
  },
  method: 'jsonp',
  request: {
    url: 'https://foo.com/bar',
    meta: {
      response: {
        ok: true
      }
    }
  },
  reason: {}
}
```
However if i change this line
```
.then(container.getUtil('handleResponse'))
```
to something like this
```
.then((response) => {
			const json = response.json()
			return response.ok
				? json
				: json.then(cause => (
					Promise.reject(newError(cause))
				))
		})
```
JSONP_FULFIL action gets dispatched
```
{
  type: 'react-redux-fetch/JSONP_FULFIL',
  resource: {
    name: 'foo'
  },
  method: 'jsonp',
  request: {
    url: 'https://foo.com/bar',
    meta: {
      response: {
        ok: true
      }
    }
  },
  value: {
    response: {
      // all the data i need is here
    }
  }
}
```
I can see all the requested data in `value` field but it never gets into the redux store. What am I doing wrong here? If you wish, I can make a PR with jsonp feature when we figure this out. Thanks in advance.

**Comment by hirviid** [comment]
Hi!

- When registering the jsonp request method, you pass in the `getReducer`. Is this your own reducer, or the one from react-redux-fetch? If it's the latter, it won't work, because it expects `react-redux-fetch/GET_FULFIL` action types and yours is `react-redux-fetch/JSONP_FULFIL`.
See also: https://github.com/hirviid/react-redux-fetch/blob/master/src/reducers/getReducer.js .

- Strange that my handleResponse.js function doesn't work, it's almost exactly the same as yours, only an additional check for content-length header and status code 204. Is it possible your api returns a 204, or a content-length header with length 0?
See also: https://github.com/hirviid/react-redux-fetch/blob/master/src/utils/handleResponse.js

**Comment by Fxlr8** [comment]
You are right, the issue was in the get reducer. I thought that this could work because jsonp request is sorta kinda like get request) I created a separate reducer for jsonp and now it works. I don't know whats wrong with handleResponse, but when I change it back to your's it stops working. 
status code is 200 and content length is greater than zero
