### ISSUE TITLE
Intercept action in saga middleware

### ISSUE THREAD

**Issue by samueldepooter** [hirviid/react-redux-fetch#22]
Hi,

Currently the request always has a defined type based on the request method, for example `react-redux-fetch/GET_REQUEST`.

Is it possible to add a custom type to intercept & handle the request in my saga middleware?

**Comment by hirviid** [comment]
Hi!

The way I intercept this in redux-saga is by doing an additional check on the resource name:

```javascript
// ... 
import { FETCH } from 'react-redux-fetch';

function* watchRequest(action) {
  if (action.resource.name !== 'myResource') {
    return;
  }

  // ... else do your thing
}

export default function* watchExample() {
  yield takeEvery(FETCH.for('get').REQUEST, watchRequest);
}
```

I'm not convinced supporting custom types is something we want. By being sure every request, fulfil and reject actions have the same action type, you can build general application logic like showing an error toast whenever you receive a REJECT. Or show a loader whenever you receive a REQUEST.
