### ISSUE TITLE
Basic auth

### ISSUE THREAD

**Issue by squall-cuckoo** [hirviid/react-redux-fetch#23]
Hi,

I tried to add in the headers  for Authentication
it doesn't seems to be reflecting.

is the headers option is working? it doesn't seems to be reflecting in my header request

**Comment by hirviid** [comment]
Hey

The option should work. Can you post the relevant piece of your code? Maybe I can see if something is wrong.

Thanks

**Comment by hirviid** [comment]
Closed due to no response.
