### ISSUE TITLE
mapDispatchToProps in connect only supports functions

### ISSUE THREAD

**Issue by dmeenhuis** [hirviid/react-redux-fetch#3]
It appears ``mapDispatchToProps`` in the connect HoC only accepts a function as a parameter.

The original ``connect`` function in ``react-redux`` also supports an object being passed. The keys/values in this object will then be bound with dispatch.

It would be nice if this scenario is also supported by this HoC.

**Comment by dmeenhuis** [comment]
Actually, in the current implementation it breaks my component, since the object I pass in, is ignored entirely. The actions my component expects to be there do not exist, since connect only passes in an empty object.

**Comment by hirviid** [comment]
Thanks! I made a more robust fix. Can you upgrade to v0.6.2?

**Comment by dmeenhuis** [comment]
Nice! Although, is this extra code even necessary? Wouldn't it be easier to just pass the value from ``componentMapDispatchToProps`` directly to ``connect`` in ``react-redux``?

From what I can tell, there doesn't seem to be any additional code in this HoC that does something with ``mapDispatchToProps``. Contrary to ``mapStateToProps``, which adds an additional value.

Might as well let ``react-redux`` figure out how to deal with the value, right? :)

**Comment by hirviid** [comment]
Indeed, the `dispatch` method is not always passed by redux. To simplify things, I was thinking to remove the  `componentMapStateToProps` and `componentMapDispatchToProps` in future versions. Move that responsibility to clients, whom will have to enhance their components with Redux `connect()` themselves. 

Example:
```js
const enhance = compose(
    connect(mapStateToProps, mapDispatchToProps), // redux connect
    reduxFetch(mapPropsToRequestsToProps) // react-redux-fetch connect
);

export default enhance(MyComponent);
```

**Comment by dmeenhuis** [comment]
Yeah that sounds like a sensible approach. The drawback of the current implementation is that you actually need a lot more knowledge of the inner workings of ``react-redux``, when all you want is basically is to only extend that functionality.

+1 for recompose :)
