### ISSUE TITLE
[0.6.2] mapDispatchToProps does not actually bind the action creators

### ISSUE THREAD

**Issue by dmeenhuis** [hirviid/react-redux-fetch#7]
The change you made yesterday to fix #3 now does pass in the object I specified, instead of an empty object. However, the functions on the object are not actually bound to dispatch, therefore rendering them useless.

I've made a change that addresses this issue. I'll submit a PR right after creating this issue. If you could have a look :)

**Comment by hirviid** [comment]
Thanks for fixing. I'll make a v0.6.3 release soon.
